import { Ionicons } from '@expo/vector-icons';
import { Stack, router } from 'expo-router';
import { useEffect, useState } from 'react';
import {
  Alert,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Eyebrow } from '@/components/Eyebrow';
import { colors, radius, spacing, type } from '@/constants/jiggo-theme';
import { getApiKey, getSettings, saveSettings, setApiKey } from '@/lib/settings';
import { clearHistory } from '@/lib/coach';
import { Settings } from '@/lib/types';

export default function SettingsScreen() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [keyDraft, setKeyDraft] = useState('');
  const [keyVisible, setKeyVisible] = useState(false);
  const [hasKey, setHasKey] = useState(false);
  const [keyStatus, setKeyStatus] = useState<'idle' | 'saving' | 'saved'>('idle');

  useEffect(() => {
    (async () => {
      const [s, k] = await Promise.all([getSettings(), getApiKey()]);
      setSettings(s);
      setHasKey(!!k);
      if (k) setKeyDraft(k);
    })();
  }, []);

  if (!settings) return null;

  const update = async (patch: Partial<Settings>) => {
    const next = await saveSettings(patch);
    setSettings(next);
  };

  const saveKey = async () => {
    setKeyStatus('saving');
    await setApiKey(keyDraft.trim() || null);
    setHasKey(!!keyDraft.trim());
    setKeyStatus('saved');
    setTimeout(() => setKeyStatus('idle'), 1200);
  };

  const resetCoach = () => {
    Alert.alert('Clear coach history?', 'This wipes all coach conversations on this device.', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Clear', style: 'destructive', onPress: () => clearHistory() },
    ]);
  };

  return (
    <SafeAreaView edges={['top']} style={styles.root}>
      <Stack.Screen options={{ title: 'Settings' }} />
      <View style={styles.header}>
        <Pressable hitSlop={10} onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={26} color={colors.textPrimary} />
        </Pressable>
        <Text style={styles.headerTitle}>Settings</Text>
        <View style={{ width: 26 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        {/* Profile */}
        <Section title="Profile">
          <Field label="Name">
            <TextInput
              style={styles.input}
              value={settings.name ?? ''}
              onChangeText={(v) => update({ name: v })}
              placeholder="Optional"
              placeholderTextColor={colors.textTertiary}
            />
          </Field>
          <Field label="Goal weight (kg)">
            <TextInput
              style={styles.input}
              value={settings.goalKg?.toString() ?? ''}
              keyboardType="decimal-pad"
              onChangeText={(v) => update({ goalKg: v ? parseFloat(v) : undefined })}
              placeholder="Optional"
              placeholderTextColor={colors.textTertiary}
            />
          </Field>
          <Field label="Units" inline>
            <View style={styles.segment}>
              {(['metric', 'imperial'] as const).map((u) => (
                <Pressable
                  key={u}
                  onPress={() => update({ units: u })}
                  style={[styles.seg, settings.units === u && styles.segActive]}>
                  <Text style={[styles.segText, settings.units === u && styles.segTextActive]}>
                    {u === 'metric' ? 'Metric · kg' : 'Imperial · lb'}
                  </Text>
                </Pressable>
              ))}
            </View>
          </Field>
        </Section>

        {/* Coach */}
        <Section
          title="Coach · Anthropic API"
          subtitle="Coach replies are generated by Claude. Your key is stored only in your device keychain.">
          <View style={styles.keyRow}>
            <TextInput
              style={[styles.input, { flex: 1, fontFamily: type.family.sans }]}
              value={keyDraft}
              onChangeText={setKeyDraft}
              placeholder="sk-ant-..."
              placeholderTextColor={colors.textTertiary}
              autoCapitalize="none"
              autoCorrect={false}
              secureTextEntry={!keyVisible}
            />
            <Pressable hitSlop={6} onPress={() => setKeyVisible((v) => !v)} style={styles.eyeBtn}>
              <Ionicons name={keyVisible ? 'eye-off-outline' : 'eye-outline'} size={18} color={colors.textTertiary} />
            </Pressable>
          </View>
          <View style={{ flexDirection: 'row', gap: spacing.sm }}>
            <Pressable style={[styles.btn, styles.btnPrimary]} onPress={saveKey}>
              <Text style={styles.btnPrimaryText}>
                {keyStatus === 'saving' ? 'Saving…' : keyStatus === 'saved' ? 'Saved ✓' : hasKey ? 'Update key' : 'Save key'}
              </Text>
            </Pressable>
            {hasKey && (
              <Pressable style={[styles.btn, styles.btnGhost]} onPress={async () => {
                setKeyDraft('');
                await setApiKey(null);
                setHasKey(false);
              }}>
                <Text style={styles.btnGhostText}>Remove</Text>
              </Pressable>
            )}
          </View>
          <Pressable style={styles.linkRow} onPress={resetCoach}>
            <Ionicons name="trash-outline" size={16} color={colors.danger} />
            <Text style={styles.linkText}>Clear coach conversation history</Text>
          </Pressable>
        </Section>

        {/* Privacy */}
        <Section
          title="Privacy"
          subtitle="JIGGO MAXXING is local-first. Scans, journal entries, plan progress, and fits never leave your device. Coach turns go only to Anthropic (when you opt in).">
          <View style={styles.privacyRow}>
            <Ionicons name="lock-closed-outline" size={18} color={colors.bronze} />
            <Text style={styles.privacyText}>
              No analytics. No accounts. No ratings. No comparisons.
            </Text>
          </View>
        </Section>

        {/* About */}
        <Section title="About">
          <InfoRow label="Version" value="1.0.0" />
          <InfoRow label="Build" value="iOS · React Native" />
          <InfoRow label="Tone" value="Insight, not judgement" />
        </Section>

        <View style={{ height: 80 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <View style={styles.section}>
      <Eyebrow>{title}</Eyebrow>
      {subtitle && <Text style={styles.sectionSubtitle}>{subtitle}</Text>}
      <View style={{ gap: spacing.md, marginTop: spacing.sm }}>{children}</View>
    </View>
  );
}

function Field({
  label,
  children,
  inline = false,
}: {
  label: string;
  children: React.ReactNode;
  inline?: boolean;
}) {
  return (
    <View style={[styles.field, inline && { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }]}>
      <Text style={styles.fieldLabel}>{label}</Text>
      <View style={inline ? undefined : { marginTop: 6 }}>{children}</View>
    </View>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.infoRow}>
      <Text style={styles.infoLabel}>{label}</Text>
      <Text style={styles.infoValue}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.ink },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  headerTitle: { color: colors.textPrimary, fontFamily: type.family.sansSemi, fontSize: 16 },
  content: { paddingHorizontal: spacing.xl, paddingTop: spacing.md, gap: spacing.xxl },

  section: { gap: spacing.sm },
  sectionSubtitle: {
    color: colors.textTertiary,
    fontFamily: type.family.sans,
    fontSize: 12.5,
    lineHeight: 18,
  },

  field: { gap: 4 },
  fieldLabel: {
    color: colors.textTertiary,
    fontFamily: type.family.sansMedium,
    fontSize: 10.5,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  input: {
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.hairline,
    backgroundColor: colors.surfaceElevated,
    color: colors.textPrimary,
    fontFamily: type.family.sansMedium,
    fontSize: 14,
  },

  segment: { flexDirection: 'row', backgroundColor: colors.surfaceElevated, borderRadius: radius.md, padding: 3 },
  seg: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: radius.sm },
  segActive: { backgroundColor: colors.bronze },
  segText: { color: colors.textSecondary, fontFamily: type.family.sansMedium, fontSize: 11 },
  segTextActive: { color: colors.textOnBronze },

  keyRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  eyeBtn: {
    width: 44, height: 44, alignItems: 'center', justifyContent: 'center',
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.hairline,
    backgroundColor: colors.surfaceElevated,
  },
  btn: {
    paddingVertical: 12,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.pill,
    alignItems: 'center',
  },
  btnPrimary: { backgroundColor: colors.bronze, flex: 1 },
  btnPrimaryText: { color: colors.textOnBronze, fontFamily: type.family.sansSemi, fontSize: 13, letterSpacing: 0.2 },
  btnGhost: { borderWidth: StyleSheet.hairlineWidth, borderColor: colors.hairline, backgroundColor: colors.surface },
  btnGhostText: { color: colors.textSecondary, fontFamily: type.family.sansMedium, fontSize: 13 },
  linkRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: spacing.md },
  linkText: { color: colors.danger, fontFamily: type.family.sansMedium, fontSize: 13 },

  privacyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: spacing.lg,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(176,138,90,0.22)',
    backgroundColor: colors.bronzeOnBlack,
  },
  privacyText: { color: colors.textPrimary, fontFamily: type.family.sansMedium, fontSize: 12.5, flex: 1, lineHeight: 18 },

  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.hairline,
  },
  infoLabel: { color: colors.textSecondary, fontFamily: type.family.sansMedium, fontSize: 13 },
  infoValue: { color: colors.textPrimary, fontFamily: type.family.sansMedium, fontSize: 13 },
});
